import type { Metadata } from "next";
import Image from "next/image";
import { PageHero } from "@/components/page-hero";
import { ContactSection } from "@/components/contact-section";

export const metadata: Metadata = { title: "Nosotros" };

export default function AboutPage() {
  return <><PageHero eyebrow="Inicio / Nosotros" title="Conoce Renacer Distribuidora" subtitle="Calidad premium, confianza y servicio para hogares y negocios de Antofagasta." image="/images/hero/about.jpg" /><section className="section container about-grid"><div><span className="eyebrow">Nuestra historia</span><h2>Más que un proveedor, somos tu aliado</h2><p>Nacimos con el propósito de elevar el estándar en la distribución de carnes. Seleccionamos cortes de proveedores confiables y mantenemos trazabilidad, frescura y calidad durante todo el proceso.</p><p>Trabajamos para construir relaciones de largo plazo basadas en confianza, transparencia y compromiso.</p></div><div className="about-image"><Image src="/images/hero/products.jpg" alt="Selección de cortes de carne" fill sizes="(max-width: 900px) 100vw, 50vw" /></div></section><section className="section section-dark"><div className="container mission-grid"><div><h2>Misión</h2><p>Abastecer con carnes premium, garantizando frescura, calidad, trazabilidad y un servicio confiable.</p></div><div><h2>Visión</h2><p>Ser la distribuidora de referencia en Antofagasta por nuestro servicio, eficiencia logística y relaciones duraderas.</p></div></div></section><section className="section container"><div className="section-heading"><div><span className="eyebrow">Nuestros valores</span><h2>Principios que nos definen</h2></div></div><div className="values-grid">{[["Calidad","Seleccionamos cortes y proveedores con estándares exigentes."],["Frescura","Mantenemos cadena de frío y procesos que aseguran calidad."],["Compromiso","Respondemos con seriedad y cumplimos lo acordado."],["Puntualidad","Programamos rutas y entregas de manera responsable."],["Confianza","Trabajamos con transparencia y trazabilidad."],["Atención cercana","Te acompañamos antes y después de tu compra."]].map(([title,text]) => <article key={title}><span>✓</span><h3>{title}</h3><p>{text}</p></article>)}</div></section><ContactSection /></>;
}
